import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'hy' | 'ru' | 'en';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  currency: string;
  formatPrice: (amount: number, forceUSD?: boolean) => string;
}

const translations: Record<Language, Record<string, string>> = {
  hy: {
    // General
    site_name: 'Armenia Freelance',
    login: 'Մուտք',
    signup: 'Գրանցում',
    logout: 'Ելք',
    become_performer: 'Դառնալ կատարող',
    become_client_btn: 'Գտնել մասնագետ',
    
    // Auth
    auth_title: 'Մուտքի արձանագրություն',
    auth_subtitle: 'Մուտք գործեք ձեր պրոֆիլ',
    email_label: 'Էլ. հասցե',
    password_label: 'Գաղտնաբառ',
    nickname_label: 'Մականուն',
    verify_code: 'Հաստատման կոդ',
    
    // Landing
    hero_title: 'Հայաստանի Լավագույն ՏՏ Մասնագետները',
    hero_subtitle: 'ԷԼԻՏԱՐ ՖՐԻԼԱՆՍ ԷԿՈՀԱՄԱԿԱՐԳ',
    hero_grid: 'ԷԼԻՏԱՐ ՑԱՆՑ',
    search_placeholder: 'Փնտրեք տեխնիկական վարպետություն կամ նախագծեր...',
    initialize_search: 'Սկսել որոնումը',
    verified_specialists: 'Ստուգված մասնագետներ',
    projected_volume: 'Նախագծված ծավալ',
    node_uptime: 'Համակարգի աշխատունակություն',
    elite_specialists: 'Էլիտար մասնագետներ',
    top_tier_performers: 'Բարձրակարգ կատարողներ',
    client_reviews: 'Հաճախորդների կարծիքները',
    success_transmissions: 'Հաջողության հաղորդումներ',
    categories_title: 'Գործառնական տիրույթներ',
    browse_all: 'Դիտել բոլորը',
    how_it_works: 'Ինչպես է այն աշխատում',
    execution_protocol: 'Կատարման արձանագրություն',
    security_escrow: 'Անվտանգություն և Էսքրոու',
    
    // Process Steps
    step_1_title: 'Սահմանել նպատակը',
    step_1_desc: 'Կազմեք ձեր նախագծի մանրամասն տեխնիկական առաջադրանքը:',
    step_2_title: 'Համապատասխանեցնել որակավորումը',
    step_2_desc: 'Վերանայեք մասնագետների առաջարկները և ստուգված պորտֆոլիոները:',
    step_3_title: 'Իրականացնել սինխրոնիզացիա',
    step_3_desc: 'Ստեղծեք անվտանգ կապ և սկսեք նախագծի իրականացումը:',
    
    // Roles
    role_freelancer: 'Ֆրիլանսեր',
    role_client: 'Պատվիրատու',
    role_agency: 'Գործակալություն',
    
    // Dashboard
    dashboard_title: 'Կառավարման վահանակ',
    my_projects: 'Իմ նախագծերը',
    messages: 'Հաղորդագրություններ',
    balance: 'Հաշվեկշիռ',
    active_missions: 'Ակտիվ առաքելություններ',
    credits: 'Կրեդիտներ',
    overview: 'Ակնարկ',
    wallet: 'Քսակ',
    trust_rating: 'Վստահության վարկանիշ',
    op_cycles: 'Գործառնական ցիկլեր',
    verification: 'Վերիֆիկացում',
    active_protocols: 'Ակտիվ արձանագրություններ',
    view_archive: 'Դիտել արխիվը',
    system_status: 'Համակարգի կարգավիճակ',
    synchronized: 'Սինխրոնիզացված',
    proposals: 'Առաջարկներ',
    audit_status: 'Աուդիտի կարգավիճակ',
    pulse: 'Էկոհամակարգի պուլս',
    
    // Auth Flow
    authentication: 'Աուտենտիկացում',
    initialization: 'Ինիցիալիզացիա',
    welcome_back: 'Բարի գալուստ',
    entry_protocol: 'Մուտքի արձանագրություն',
    email_identity: 'Էլ. հասցե',
    nickname_tag: 'Մականուն',
    password_key: 'Գաղտնաբառ',
    confirm_key: 'Հաստատել գաղտնաբառը',
    authorize_access: 'Լիազորել մուտքը',
    initiate_protocol: 'Սկսել արձանագրությունը',
    external_gateways: 'Արտաքին մուտքեր',
    security_audit: 'Անվտանգության աուդիտ',
    confirm_identity: 'Հաստատել ինքնությունը',
    path_selection: 'Ուղու ընտրություն',
    specialist_arch: 'Մասնագիտական ճարտարապետություն',
    agency_infra: 'Գործակալության ենթակառուցվածք',
    client_procurement: 'Պատվիրատուի գնումներ',
    proceed_profiling: 'Անցնել պրոֆիլավորմանը',
    profile_genesis: 'Պրոֆիլի ստեղծում',
    deploy_identity: 'Տեղադրել ինքնությունը',
    
    // Specialist Catalog
    specialist_registry: 'Մասնագետների ռեգիստր',
    geo_nodes: 'Աշխարհագրական հանգույցներ',
    valuation_range: 'Գնահատման միջակայք',
    mastery_level: 'Վարպետության մակարդակ',
    apply_filters: 'Կիրառել ֆիլտրման արձանագրությունը',
    sort_by: 'Տեսակավորել ըստ',
    rating_protocol: 'Վարկանիշի արձանագրություն',
    valuation_low_high: 'Գնահատում (ցածր-բարձր)',
    active_responses: 'Ակտիվ արձագանքներ',
    new_registry: 'Նոր ռեգիստր',
    missions: 'Առաքելություններ',
    audit_node: 'Աուդիտի հանգույց',
    
    // Job Details
    return_registry: 'Վերադառնալ ռեգիստր',
    asset_audit: 'Արձանագրություն. Ակտիվների աուդիտ',
    technical_brief: 'Տեխնիկական բրիֆ',
    complexity_level: 'Բարդության մակարդակ',
    escrow_security: 'Էսքրոու անվտանգություն',
    neural_responses: 'Նյարդային պատասխաններ',
    valuation_proposal: 'Գնահատման առաջարկ',
    initiate_sync: 'Նախաձեռնել սինխրոնիզացիա',
    initiate_proposal: 'Նախաձեռնել առաջարկ',
    proposal_broadcasted: 'Առաջարկը հեռարձակված է',
    proposal_deployment: 'Առաջարկի տեղադրում',
    broadcast_for: 'Հեռարձակում համար',
    operational_narrative: 'Գործառնական պատմություն',
    execute_transmission: 'Կատարել փոխանցում',
    sync_requirements: 'Սինխրոնիզացման պահանջներ',
    abort_procedure: 'Ընդհատել ընթացակարգը',
    tech_approach_placeholder: 'Մանրամասնեք ձեր տեխնիկական մոտեցումը և ճարտարապետական համապատասխանությունը այս կոնկրետ նպատակի համար...',
    neural_match: 'Նյարդային համապատասխանություն',
    deadline_24h: '24-ժամյա վերջնաժամկետ',
    bid_credit_notice: 'Տվյալները կհեռարձակվեն հաճախորդին: Այս գործողությունը սպառում է 1 Bid Credit:',
    senior_arch: 'Ավագ ճարտարապետություն',
    multisig_enabled: 'Multi-Sig միացված է',
    mock_msg_1: 'Նյարդային տվյալների սինխրոնացում...',
    mock_msg_2: 'Էսքրոու արձանագրությունը հաստատված է:',
    mock_msg_3: 'Վիզուալ բրիֆի մշակում:',
    chat_time_ago: '2ր առաջ',
    msg_demo_1: 'Ողջույն: Ես վերանայել եմ Armenia Fintech նախագծի տեխնիկական բրիֆը: Ճարտարապետական պահանջները հստակ են:',
    msg_demo_2: 'Գերազանց է: Որքա՞ն է ձեր առաջարկած ժամկետը առաջին նյարդային սինխրոնացման ցիկլի համար:',
    msg_demo_3: 'Ես գնահատում եմ 5 ցիկլ նախնական տեղադրման համար: Մենք կարող ենք այսօր նախաձեռնել էսքրոուն:',
    id_label: 'ID',
    initiate_service: 'Նախաձեռնել ծառայություն',
    visual_brand_arch: 'Վիզուալ բրենդի ճարտարապետություն',
    full_stack_cluster: 'Full-Stack տեղադրման կլաստեր',
    react_arch: 'React ճարտարապետություն',
    node_infra: 'Node ենթակառուցվածք',
    aws_deployment: 'AWS տեղադրում',
    ui_ux_sync: 'UI/UX սինխրոնացում',
    domain_mobile_arch: 'Բջջային ճարտարապետություն',
    domain_neural_networks: 'Նյարդային ցանցեր (AI)',
    objective_placeholder: 'Ճարտարապետական նախագծում Armenia Fintech-ի համար...',
    budget_placeholder: '500000',
    tech_brief_placeholder: 'Մանրամասնեք ճարտարապետական բարդության և ակնկալվող արդյունքների մասին...',
    security_escrow_title: 'Multi-Sig Էսքրոու',
    security_escrow_desc: 'Արժեքը պաշտպանված է մինչև աուդիտի ավարտը:',
    elite_matching_title: 'Էլիտար համապատասխանություն',
    elite_matching_desc: 'Սինխրոնացված Tier 1 մասնագետների հետ:',
    verified_protocol_title: 'Ստուգված արձանագրություն',
    verified_protocol_desc: 'Բոլոր փոխազդեցությունները գրանցվում և աուդիտի են ենթարկվում:',
    
    // Profile
    configure_profile: 'Կարգավորել պրոֆիլը',
    trust_index: 'Վստահության ինդեքս',
    missions_done: 'Ավարտված առաքելություններ',
    initiate_dialogue: 'Նախաձեռնել երկխոսություն',
    core_skillsets: 'Հիմնական հմտություններ',
    identity_narrative: 'Ինքնության պատմություն',
    visual_archive: 'Վիզուալ արխիվ',
    preset_services: 'Կանխորոշված ծառայություններ',
    feedback_logs: 'Հետադարձ կապի մատյաններ',
    expert: 'Փորձագետ',
    intermediate: 'Միջին',
    yerevan: 'Երևան',
    no_bio: 'Ռեգիստրում դեռևս տեխնիկական պատմություն չկա: Մասնագետը կենտրոնանում է բարձրակարգ ճարտարապետական տեղակայման և միջֆունկցիոնալ սինխրոնացման վրա:',
    
    // Admin
    command_center: 'Հրամանատարական կենտրոն',
    oversight_active: 'Համաշխարհային վերահսկողությունն ակտիվ է | Համակարգի վարպետի մակարդակ',
    neural_registry: 'Նյարդային ռեգիստր',
    intel: 'Հետախուզություն',
    synced_nodes: 'Սինխրոնացված հանգույցներ',
    registry_total: 'Ընդհանուր ռեգիստր',
    active_clusters: 'Ակտիվ կլաստերներ',
    secured_deals: 'Ապահովված գործարքներ',
    scan_registry_placeholder: 'Սկանավորել նյարդային ռեգիստրը (email, nickname, IP)...',
    identity_node: 'Ինքնության հանգույց',
    protocol_role: 'Արձանագրության դեր',
    ip_address: 'IP հասցե',
    registry_date: 'Գրանցման ամսաթիվ',
    ops: 'Գործողություններ',
    cluster_distribution: 'Կլաստերների բաշխում',
    armenia_node: 'Հայաստան (Հիմնական հանգույց)',
    russia_cluster: 'Ռուսաստանի կլաստեր',
    usa_europe: 'ԱՄՆ / Եվրոպա',
    others: 'Այլք',
    registry_velocity: 'Ռեգիստրի արագություն',
    last_24_cycles: 'Վերջին 24 ցիկլերի գործողությունները',
    protocol_economy: 'Արձանագրության տնտեսություն (Connects)',
    update_rates: 'Թարմացնել սակագները',
    base_commission: 'Բազային միջնորդավճար',
    platform_fee_desc: 'Հարթակի վճար յուրաքանչյուր գործարքի հանգույցի համար',
    credit_valuation: 'Վարկային գնահատում',
    price_per_bid: 'Գինը մեկ հայտի համար',
    free_allocation: 'Անվճար հատկացում',
    initial_credits_desc: 'Նախնական կրեդիտներ նոր հանգույցների համար',
    freelancer: 'Ֆրիլանսեր',
    client: 'Հաճախորդ',
    
    // Messages
    dialogue_tunnels: 'Երկխոսության թունելներ',
    secure_matrix: 'Ապահով հաղորդակցության մատրիցան ակտիվ է',
    search_tunnels: 'Որոնել թունելները...',
    confirm_completion: 'Հաստատել ավարտը',
    verified_sync: 'Վերիֆիկացված սինխրոնացում',
    encryption_active: 'End-to-End կոդավորման արձանագրությունն ակտիվ է',
    type_transmission: 'Մուտքագրեք ձեր հաղորդագրությունը...',
    initialize_dialogue: 'Նախաձեռնել երկխոսություն',
    select_node_sync: 'Ընտրեք հանգույց ռեգիստրից սինխրոնացումը սկսելու համար',
    
    // Specialists
    specialist_registry: 'Մասնագետների ռեգիստր',
    neural_match: 'Նյարդային համապատասխանություն',
    rating_protocol: 'Վարկանիշային արձանագրություն',
    mastery_level: 'Վարպետության մակարդակ',
    apply_filters: 'Կիրառել ֆիլտրի արձանագրությունը',
    valuation_range: 'Գնահատման միջակայք',
    mastery_expert: 'Փորձագետ',
    mastery_senior: 'Ավագ',
    mastery_entry: 'Սկսնակ',
    domain_software: 'Ծրագրային ապահովում',
    domain_visual: 'Վիզուալ ինքնություն',
    domain_data: 'Տվյալների ճարտարապետություն',
    domain_cyber: 'Կիբերանվտանգություն',
    loc_yerevan: 'Երևան (Գլխավոր)',
    loc_gyumri: 'Գյումրու կլաստեր',
    loc_dilijan: 'Դիլիջանի հաբ',
    loc_remote: 'Հեռակա սինխրոնացում',
    min: 'Մին',
    max: 'Մաքս',
    mastery_expert_yrs: 'Փորձագետ (8+ տարի)',
    mastery_intermediate: 'Միջին',
    mastery_beginner: 'Սկսնակ հանգույց',
    
    // Categories
    cat_software: 'Ծրագրային ապահովում',
    cat_software_desc: 'Full-stack, Backend և Ճարտարապետական նախագծում:',
    cat_mobile: 'Բջջային էկոհամակարգեր',
    cat_mobile_desc: 'iOS, Android և Cross-platform գերազանցություն:',
    cat_visual: 'Վիզուալ ինքնություն',
    cat_visual_desc: 'Բարձրակարգ UI/UX և բրենդի ճարտարապետություն:',
    cat_data: 'Տվյալների ճարտարապետություն',
    cat_data_desc: 'Նյարդային ցանցեր և մասշտաբավորվող տվյալների մոդելներ:',
    cat_cyber: 'Կիբերանվտանգություն',
    cat_cyber_desc: 'Ենթակառուցվածքների աուդիտ և պաշտպանության արձանագրություններ:',
    cat_growth: 'Աճի ռազմավարություններ',
    cat_growth_desc: 'Շուկա ներթափանցում և թվային ներկայություն:',
    
    // Reviews
    review_1: 'Հայկական կլաստերի տեխնիկական փորձաքննության մակարդակն անգերազանցելի է: 3 ցիկլում սինխրոնացրել ենք ամբողջական բանկային միջուկը:',
    review_2: 'Ճարտարապետական ճշգրտություն և կատարյալ հաղորդակցություն: Հարթակը անթերի կառավարեց էսքրոու արձանագրությունը:',
    review_3: '24 ժամվա ընթացքում գտա նյարդային ցանցի մասնագիտացված ինժեներ: Մասշտաբավորումը երբեք այսքան արդյունավետ չի եղել:',
    
    // Security
    security_escrow: 'Անվտանգության էսքրոու',
    security_desc: 'Բոլոր արժեքային փոխանցումները պաշտպանված են բազմաստորագրային էսքրոուով: Միջոցները թողարկվում են միայն ստուգված փուլի ավարտից հետո:',
    
    // Auth
    ceo_placeholder: 'Տնօրեն Fintech Solutions-ում',
    specialist_placeholder: 'Նյարդային ենթակառուցվածքների ավագ ճարտարապետ',
    rate_usd: 'Սակագին (USD)',
    invalid_code_alert: 'Անվավեր կոդ: Սիմուլյացիայի համար օգտագործեք 1234:',
    code_transmitted: 'Կոդը փոխանցվել է',
    total_rating: 'Ընդհանուր',
    milestones: 'Փուլեր',
    tier_1: 'ՄԱԿԱՐԴԱԿ 1',
    audit_passed: 'Աուդիտն անցած է',
    pulse: 'Պուլս',
    new_proposal_notif: 'Նոր հայտ է ստացվել «Neural Architecture»-ի համար',
    balance_update_notif: 'Հաշվեկշռի թարմացում. +14,500 AMD',
    
    // Post Job
    post_job: 'Տեղադրել նախագիծ',
    find_work: 'Գտնել աշխատանք',
    budget: 'Բյուջե',
    deadline: 'Վերջնաժամկետ',
    mission_registry: 'Առաքելությունների ռեեստր',
    registry_subtitle: 'Ստուգեք ակտիվ նպատակները Հայաստանի տեխնիկական ցանցում',
    project_protocol: 'Նախագծի արձանագրություն',
    fixed_price: 'Ֆիքսված գին',
    hourly_sync: 'Ժամավճար',
    retainer_node: 'Ռետեյներ',
    complexity_level: 'Բարդության մակարդակ',
    expert_arch: 'Փորձագիտական ճարտարապետություն',
    standard_impl: 'Ստանդարտ իրականացում',
    entry_task: 'Մեկնարկային առաջադրանք',
    budget_allocation: 'Բյուջեի բաշխում',
    scan_registry: 'Սկանավորել ռեեստրը',
    no_missions: 'Ակտիվ առաքելություններ չեն հայտնաբերվել:',
    proposals_received: 'Առաջարկ ստացված',
    resource_allocation: 'Ռեսուրսների բաշխում',
    audit_objective: 'Ստուգել նպատակը',
    
    // Post Job
    initiate_request: 'Նախաձեռնել հարցում',
    broadcasting: 'Հեռարձակում էլիտար մասնագետների ցանցին',
    objective_title: 'Նպատակի վերնագիր',
    operational_domain: 'Գործառնական տիրույթ',
    technical_brief: 'Տեխնիկական ամփոփագիր',
    deploy_mission: 'Տեղադրել առաքելությունը ռեեստրում',
    abort_deployment: 'Ընդհատել տեղադրումը'
  },
  ru: {
    site_name: 'Armenia Freelance',
    login: 'Вход',
    signup: 'Регистрация',
    logout: 'Выход',
    become_performer: 'Стать исполнителем',
    become_client_btn: 'Найти специалиста',
    
    auth_title: 'Протокол доступа',
    auth_subtitle: 'Синхронизируйтесь с профилем',
    email_label: 'Электронная почта',
    password_label: 'Пароль',
    nickname_label: 'Никнейм',
    verify_code: 'Код подтверждения',
    
    hero_title: 'Лучшие IT-специалисты Армении',
    hero_subtitle: 'ЭЛИТНАЯ ФРИЛАНС-ЭКОСИСТЕМА',
    hero_grid: 'ЭЛИТНАЯ СЕТЬ',
    search_placeholder: 'Поиск технического мастерства или проектов...',
    initialize_search: 'Начать поиск',
    verified_specialists: 'Проверенные специалисты',
    projected_volume: 'Прогнозируемый объем',
    node_uptime: 'Аптайм системы',
    elite_specialists: 'Элитные специалисты',
    top_tier_performers: 'Топ-исполнители',
    client_reviews: 'Отзывы клиентов',
    success_transmissions: 'Передачи успеха',
    categories_title: 'Операционные области',
    browse_all: 'Посмотреть все',
    how_it_works: 'Как это работает',
    execution_protocol: 'Протокол выполнения',
    security_escrow: 'Безопасность и Эскроу',
    
    step_1_title: 'Определить цель',
    step_1_desc: 'Составьте детальный технический бриф для вашего проекта.',
    step_2_title: 'Сопоставить квалификацию',
    step_2_desc: 'Просмотрите предложения специалистов и проверенные портфолио.',
    step_3_title: 'Выполнить синхронизацию',
    step_3_desc: 'Установите защищенное соединение и начните развертывание.',
    
    role_freelancer: 'Фрилансер',
    role_client: 'Заказчик',
    role_agency: 'Агентство',
    
    dashboard_title: 'Панель управления',
    my_projects: 'Мои проекты',
    messages: 'Сообщения',
    balance: 'Баланс',
    active_missions: 'Активные миссии',
    credits: 'Кредиты',
    overview: 'Обзор',
    wallet: 'Кошелек',
    trust_rating: 'Рейтинг доверия',
    op_cycles: 'Операционные циклы',
    verification: 'Верификация',
    active_protocols: 'Активные протоколы',
    view_archive: 'Посмотреть архив',
    system_status: 'Статус системы',
    synchronized: 'Синхронизировано',
    proposals: 'Предложения',
    audit_status: 'Статус аудита',
    pulse: 'Пульс экосистемы',
    
    // Auth Flow
    authentication: 'Аутентификация',
    initialization: 'Инициализация',
    welcome_back: 'С возвращением',
    entry_protocol: 'Протокол входа',
    email_identity: 'Эл. почта',
    nickname_tag: 'Никнейм',
    password_key: 'Пароль',
    confirm_key: 'Подтвердить пароль',
    authorize_access: 'Авторизовать доступ',
    initiate_protocol: 'Начать протокол',
    external_gateways: 'Внешние шлюзы',
    security_audit: 'Аудит безопасности',
    confirm_identity: 'Подтвердить личность',
    path_selection: 'Выбор пути',
    specialist_arch: 'Архитектура специалиста',
    agency_infra: 'Инфраструктура агентства',
    client_procurement: 'Закупки клиента',
    proceed_profiling: 'Перейти к профилированию',
    profile_genesis: 'Создание профиля',
    deploy_identity: 'Развернуть личность',
    
    // Specialist Catalog
    specialist_registry: 'Реестр специалистов',
    geo_nodes: 'Географические узлы',
    valuation_range: 'Диапазон оценки',
    mastery_level: 'Уровень мастерства',
    apply_filters: 'Применить протокол фильтрации',
    sort_by: 'Сортировать по',
    rating_protocol: 'Протокол рейтинга',
    valuation_low_high: 'Оценка (низкая-высокая)',
    active_responses: 'Активные ответы',
    new_registry: 'Новый реестр',
    missions: 'Миссии',
    audit_node: 'Аудит узла',
    
    // Job Details
    return_registry: 'Вернуться в реестр',
    asset_audit: 'Протокол: Аудит активов',
    technical_brief: 'Технический бриф',
    complexity_level: 'Уровень сложности',
    escrow_security: 'Безопасность эскроу',
    neural_responses: 'Отклики сети',
    valuation_proposal: 'Предложение по стоимости',
    initiate_sync: 'Начать синхронизацию',
    initiate_proposal: 'Подать предложение',
    proposal_broadcasted: 'Предложение отправлено',
    proposal_deployment: 'Развертывание предложения',
    broadcast_for: 'Трансляция для',
    operational_narrative: 'Описание подхода',
    execute_transmission: 'Выполнить передачу',
    sync_requirements: 'Требования синхронизации',
    abort_procedure: 'Прервать процедуру',
    tech_approach_placeholder: 'Подробно опишите ваш технический подход и архитектурное соответствие для этой конкретной задачи...',
    neural_match: 'Нейронное соответствие',
    deadline_24h: '24ч дедлайн',
    bid_credit_notice: 'Данные будут переданы клиенту. Это действие стоит 1 Bid Credit.',
    senior_arch: 'Старшая архитектура',
    multisig_enabled: 'Multi-Sig включен',
    mock_msg_1: 'Синхронизация нейронных данных...',
    mock_msg_2: 'Протокол эскроу подтвержден.',
    mock_msg_3: 'Составление визуального брифа.',
    chat_time_ago: '2м назад',
    msg_demo_1: 'Привет! Я изучил технический бриф проекта Armenia Fintech. Архитектурные требования ясны.',
    msg_demo_2: 'Отлично. Каковы ваши предполагаемые сроки для первого цикла нейронной синхронизации?',
    msg_demo_3: 'Я оцениваю в 5 циклов для первоначального развертывания. Мы можем инициировать эскроу сегодня.',
    id_label: 'ID',
    initiate_service: 'Инициировать услугу',
    visual_brand_arch: 'Архитектура визуального бренда',
    full_stack_cluster: 'Кластер Full-Stack развертывания',
    react_arch: 'React архитектура',
    node_infra: 'Node инфраструктура',
    aws_deployment: 'AWS развертывание',
    ui_ux_sync: 'UI/UX синхронизация',
    domain_mobile_arch: 'Мобильная архитектура',
    domain_neural_networks: 'Нейронные сети (AI)',
    objective_placeholder: 'Архитектурное проектирование для Armenia Fintech...',
    budget_placeholder: '500000',
    tech_brief_placeholder: 'Подробно опишите архитектурную сложность и ожидаемые результаты...',
    security_escrow_title: 'Multi-Sig Эскроу',
    security_escrow_desc: 'Стоимость защищена до завершения аудита.',
    elite_matching_title: 'Элитное соответствие',
    elite_matching_desc: 'Синхронизировано со специалистами Tier 1.',
    verified_protocol_title: 'Проверенный протокол',
    verified_protocol_desc: 'Все взаимодействия регистрируются и проверяются.',
    
    // Profile
    configure_profile: 'Настроить профиль',
    trust_index: 'Индекс доверия',
    missions_done: 'Миссий выполнено',
    initiate_dialogue: 'Начать диалог',
    core_skillsets: 'Ключевые навыки',
    identity_narrative: 'Личная история',
    visual_archive: 'Визуальный архив',
    preset_services: 'Готовые услуги',
    feedback_logs: 'Журнал отзывов',
    expert: 'Эксперт',
    intermediate: 'Средний',
    yerevan: 'Ереван',
    no_bio: 'Техническое описание в реестре пока отсутствует. Специалист специализируется на высокоуровневом архитектурном развертывании и кросс-функциональной синхронизации.',
    
    // Admin
    command_center: 'Центр управления',
    oversight_active: 'Глобальный надзор активен | Уровень Мастера Системы',
    neural_registry: 'Нейронный реестр',
    intel: 'Разведка',
    synced_nodes: 'Синхронизировано узлов',
    registry_total: 'Всего в реестре',
    active_clusters: 'Активные кластеры',
    secured_deals: 'Защищенные сделки',
    scan_registry_placeholder: 'Сканировать реестр (email, ник, IP)...',
    identity_node: 'Узел личности',
    protocol_role: 'Роль протокола',
    ip_address: 'IP адрес',
    registry_date: 'Дата регистрации',
    ops: 'Опции',
    cluster_distribution: 'Распределение кластеров',
    armenia_node: 'Армения (Главный узел)',
    russia_cluster: 'Российский кластер',
    usa_europe: 'США / Европа',
    others: 'Другие',
    registry_velocity: 'Скорость реестра',
    last_24_cycles: 'Активность за последние 24 цикла',
    protocol_economy: 'Экономика протокола (Коннекты)',
    update_rates: 'Обновить тарифы',
    base_commission: 'Базовая комиссия',
    platform_fee_desc: 'Комиссия платформы за узел транзакции',
    credit_valuation: 'Оценка кредита',
    price_per_bid: 'Цена за один отклик',
    free_allocation: 'Бесплатное выделение',
    initial_credits_desc: 'Начальные кредиты для новых узлов',
    freelancer: 'Фрилансер',
    client: 'Клиент',
    
    // Messages
    dialogue_tunnels: 'Туннели диалога',
    secure_matrix: 'Защищенная матрица связи активна',
    search_tunnels: 'Поиск туннелей...',
    confirm_completion: 'Подтвердить завершение',
    verified_sync: 'Верифицированная синхронизация',
    encryption_active: 'Протокол сквозного шифрования активен',
    type_transmission: 'Введите ваше сообщение...',
    initialize_dialogue: 'Инициализировать диалог',
    select_node_sync: 'Выберите узел из реестра для начала синхронизации',
    
    // Specialists
    specialist_registry: 'Реестр специалистов',
    neural_match: 'Нейронное соответствие',
    rating_protocol: 'Протокол рейтинга',
    mastery_level: 'Уровень мастерства',
    apply_filters: 'Применить фильтры',
    valuation_range: 'Диапазон оценки',
    mastery_expert: 'Эксперт',
    mastery_senior: 'Старший',
    mastery_entry: 'Младший',
    domain_software: 'Разработка ПО',
    domain_visual: 'Визуальный стиль',
    domain_data: 'Архитектура данных',
    domain_cyber: 'Кибербезопасность',
    loc_yerevan: 'Ереван (Центр)',
    loc_gyumri: 'Гюмрийский кластер',
    loc_dilijan: 'Дիլիջան Հաբ',
    loc_remote: 'Удаленно',
    min: 'Мин',
    max: 'Макс',
    mastery_expert_yrs: 'Эксперт (8+ лет)',
    mastery_intermediate: 'Средний',
    mastery_beginner: 'Начальный узел',
    
    // Categories
    cat_software: 'Разработка ПО',
    cat_software_desc: 'Full-stack, Backend и архитектурное проектирование.',
    cat_mobile: 'Мобильные экосистемы',
    cat_mobile_desc: 'iOS, Android и кроссплатформенное превосходство.',
    cat_visual: 'Визуальный стиль',
    cat_visual_desc: 'Высокоуровневый UI/UX и архитектура бренда.',
    cat_data: 'Архитектура данных',
    cat_data_desc: 'Нейронные сети и масштабируемые модели данных.',
    cat_cyber: 'Кибербезопасность',
    cat_cyber_desc: 'Аудит инфраструктуры и протоколы защиты.',
    cat_growth: 'Стратегии роста',
    cat_growth_desc: 'Проникновение на рынок и цифровое присутствие.',
    
    // Reviews
    review_1: 'Уровень технической экспертизы в армянском кластере не имеет равных. Синхронизировали банковское ядро за 3 цикла.',
    review_2: 'Архитектурная точность и идеальная коммуникация. Платформа безупречно справилась с протоколом эскроу.',
    review_3: 'Нашел специализированного инженера по нейросетям за 24 часа. Масштабирование еще никогда не было таким эффективным.',
    
    // Security
    security_escrow: 'Безопасный эскроу',
    security_desc: 'Все переводы защищены мультиподписным эскроу. Средства высвобождаются только после подтверждения этапа.',
    
    // Auth
    ceo_placeholder: 'CEO в Fintech Solutions',
    specialist_placeholder: 'Старший архитектор нейроинфраструктуры',
    rate_usd: 'Ставка (USD)',
    invalid_code_alert: 'Неверный код. Используйте 1234 для симуляции.',
    code_transmitted: 'Код отправлен на',
    total_rating: 'Всего',
    milestones: 'Этапы',
    tier_1: 'УРОВЕНЬ 1',
    audit_passed: 'Аудит пройден',
    pulse: 'Пульс',
    new_proposal_notif: 'Получена новая заявка для "Neural Architecture"',
    balance_update_notif: 'Обновление баланса: +14,500 AMD',
    
    post_job: 'Разместить проект',
    find_work: 'Найти работу',
    budget: 'Бюджет',
    deadline: 'Дедлайн',
    mission_registry: 'Реестр миссий',
    registry_subtitle: 'Проверьте активные цели в технической сети Армении',
    project_protocol: 'Протокол проекта',
    fixed_price: 'Фиксированная цена',
    hourly_sync: 'Почасовая оплата',
    retainer_node: 'Ретейнер',
    complexity_level: 'Уровень сложности',
    expert_arch: 'Экспертная архитектура',
    standard_impl: 'Стандартная реализация',
    entry_task: 'Начальная задача',
    budget_allocation: 'Распределение бюджета',
    scan_registry: 'Сканировать реестр',
    no_missions: 'Активных миссий не обнаружено.',
    proposals_received: 'Предложений получено',
    resource_allocation: 'Распределение ресурсов',
    audit_objective: 'Проверить цель',
    
    initiate_request: 'Инициировать запрос',
    broadcasting: 'Трансляция сети элитных специалистов',
    objective_title: 'Заголовок цели',
    operational_domain: 'Операционная область',
    technical_brief: 'Технический бриф',
    deploy_mission: 'Развернуть миссию в реестре',
    abort_deployment: 'Прервать развертывание'
  },
  en: {
    site_name: 'Armenia Freelance',
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Logout',
    become_performer: 'Become a Performer',
    become_client_btn: 'Find Specialist',
    
    auth_title: 'Access Protocol',
    auth_subtitle: 'Synchronize with your profile',
    email_label: 'Email Address',
    password_label: 'Password',
    nickname_label: 'Nickname',
    verify_code: 'Verification Code',
    
    hero_title: 'Armenia\'s Elite IT Network',
    hero_subtitle: 'PREMIUM FREELANCE ECOSYSTEM',
    hero_grid: 'ELITE GRID',
    search_placeholder: 'Scan for technical mastery or project objectives...',
    initialize_search: 'Initialize Search',
    verified_specialists: 'Verified Specialists',
    projected_volume: 'Projected Volume',
    node_uptime: 'Node Uptime',
    elite_specialists: 'Elite Specialists',
    top_tier_performers: 'Top-Tier Performers',
    client_reviews: 'Client Reviews',
    success_transmissions: 'Success Transmissions',
    categories_title: 'Operational Domains',
    browse_all: 'Browse All Segments',
    how_it_works: 'How it Works',
    execution_protocol: 'Execution Protocol',
    security_escrow: 'Security & Escrow Layer',
    
    step_1_title: 'Define Objective',
    step_1_desc: 'Draft a detailed architectural brief for your project.',
    step_2_title: 'Match Credentials',
    step_2_desc: 'Review elite specialist proposals and verified portfolios.',
    step_3_title: 'Execute Sync',
    step_3_desc: 'Establish a secure tunnel and begin architectural deployment.',
    
    role_freelancer: 'Freelancer',
    role_client: 'Client',
    role_agency: 'Agency',
    
    dashboard_title: 'Dashboard',
    my_projects: 'My Projects',
    messages: 'Messages',
    balance: 'Balance',
    active_missions: 'Active Missions',
    credits: 'Credits',
    overview: 'Overview',
    wallet: 'Wallet',
    trust_rating: 'Trust Rating',
    op_cycles: 'Operational Cycles',
    verification: 'Verification',
    active_protocols: 'Active Protocols',
    view_archive: 'View Archive',
    system_status: 'System Status',
    synchronized: 'Synchronized',
    proposals: 'Proposals',
    audit_status: 'Audit Status',
    pulse: 'Ecosystem Pulse',
    
    // Auth Flow
    authentication: 'Authentication',
    initialization: 'Initialization',
    welcome_back: 'Welcome Back',
    entry_protocol: 'Entry Protocol',
    email_identity: 'Satellite Identity (Email)',
    nickname_tag: 'Visual Tag (Nickname)',
    password_key: 'Access Key (Password)',
    confirm_key: 'Confirm Access Key',
    authorize_access: 'Authorize Access',
    initiate_protocol: 'Initiate Protocol',
    external_gateways: 'External Gateways',
    security_audit: 'Security Audit',
    confirm_identity: 'Confirm Identity',
    path_selection: 'Path Selection',
    specialist_arch: 'Specialist Architecture',
    agency_infra: 'Agency Infrastructure',
    client_procurement: 'Client Procurement',
    proceed_profiling: 'Proceed to Profiling',
    profile_genesis: 'Profile Genesis',
    deploy_identity: 'Deploy Identity',
    
    // Specialist Catalog
    specialist_registry: 'Specialist Registry',
    geo_nodes: 'Geographical Nodes',
    valuation_range: 'Valuation Range',
    mastery_level: 'Mastery Level',
    apply_filters: 'Apply Filter Protocol',
    sort_by: 'Sort By',
    rating_protocol: 'Rating Protocol',
    valuation_low_high: 'Valuation (Low-High)',
    active_responses: 'Active Responses',
    new_registry: 'New Registry',
    missions: 'Missions',
    audit_node: 'Audit Node',
    
    // Job Details
    return_registry: 'Return to Registry',
    asset_audit: 'Protocol: Asset Audit',
    technical_brief: 'Technical Brief',
    complexity_level: 'Complexity Level',
    escrow_security: 'Escrow Security',
    neural_responses: 'Neural Responses',
    valuation_proposal: 'Valuation Proposal',
    initiate_sync: 'Initiate Sync',
    initiate_proposal: 'Initiate Proposal',
    proposal_broadcasted: 'Proposal Broadcasted',
    proposal_deployment: 'Proposal Deployment',
    broadcast_for: 'Broadcast for',
    operational_narrative: 'Operational Narrative',
    execute_transmission: 'Execute Transmission',
    sync_requirements: 'Sync Requirements',
    abort_procedure: 'Abort Procedure',
    tech_approach_placeholder: 'Detail your technical approach and architectural fit for this specific objective...',
    neural_match: 'Neural Match',
    deadline_24h: '24H Deadline',
    bid_credit_notice: 'Credentials will be broadcasted to the client. This action consumes 1 Bid Credit.',
    senior_arch: 'Senior Architecture',
    multisig_enabled: 'Multi-Sig Enabled',
    mock_msg_1: 'Synchronizing neural data...',
    mock_msg_2: 'Escrow protocol confirmed.',
    mock_msg_3: 'Drafting visual brief.',
    chat_time_ago: '2m ago',
    msg_demo_1: 'Hello! I\'ve reviewed the technical brief for the Armenia Fintech project. The architectural requirements are clear.',
    msg_demo_2: 'Excellent. What\'s your proposed timeline for the first neural sync cycle?',
    msg_demo_3: 'I estimate 5 cycles for initial deployment. We can initiate the escrow today.',
    id_label: 'ID',
    initiate_service: 'Initiate Service',
    visual_brand_arch: 'Visual Brand Architecture',
    full_stack_cluster: 'Full-Stack Deployment Cluster',
    react_arch: 'React Architecture',
    node_infra: 'Node Infrastructure',
    aws_deployment: 'AWS Deployment',
    ui_ux_sync: 'UI/UX Sync',
    domain_mobile_arch: 'Mobile Architecture',
    domain_neural_networks: 'Neural Networks (AI)',
    objective_placeholder: 'Architectural Design for Armenia Fintech...',
    budget_placeholder: '500000',
    tech_brief_placeholder: 'Elaborate on the architectural complexity and outcome expectations...',
    security_escrow_title: 'Multi-Sig Escrow',
    security_escrow_desc: 'Value protected until audit completion.',
    elite_matching_title: 'Elite Matching',
    elite_matching_desc: 'Synchronized with Tier 1 specialists.',
    verified_protocol_title: 'Verified Protocol',
    verified_protocol_desc: 'All interactions are logged and audited.',
    id_label: 'ID',
    min_budget: 'Min AMD',
    max_budget: 'Max AMD',
    
    // Profile
    configure_profile: 'Configure Profile',
    trust_index: 'Trust Index',
    missions_done: 'Missions Done',
    initiate_dialogue: 'Initiate Dialogue',
    core_skillsets: 'Core Skillsets',
    identity_narrative: 'Identity Narrative',
    visual_archive: 'Visual Archive',
    preset_services: 'Pre-set Services',
    feedback_logs: 'Feedback Logs',
    initiate_service: 'Initiate Service',
    expert: 'Expert',
    intermediate: 'Intermediate',
    synchronized: 'Synchronized',
    yerevan: 'Yerevan',
    no_bio: 'No technical narrative injected into the registry yet. Specialist focuses on high-end architectural deployment and cross-functional synchronization.',
    
    // Admin
    command_center: 'Command Center',
    oversight_active: 'Global Oversight Active | System Master Level',
    neural_registry: 'Neural Registry',
    intel: 'Intel',
    synced_nodes: 'Synced Nodes',
    registry_total: 'Registry Total',
    active_clusters: 'Active Clusters',
    secured_deals: 'Secured Deals',
    scan_registry_placeholder: 'Scan neural registry (email, nickname, IP)...',
    identity_node: 'Identity Node',
    protocol_role: 'Protocol Role',
    ip_address: 'IP Address',
    registry_date: 'Registry Date',
    ops: 'Ops',
    cluster_distribution: 'Cluster Distribution',
    armenia_node: 'Armenia (Main Node)',
    russia_cluster: 'Russia Cluster',
    usa_europe: 'USA / Europe',
    others: 'Others',
    registry_velocity: 'Registry Velocity',
    last_24_cycles: 'Last 24 Cycles Activities',
    protocol_economy: 'Protocol Economy (Connects)',
    update_rates: 'Update Rates',
    base_commission: 'Base Commission',
    platform_fee_desc: 'Platform fee per transaction node',
    credit_valuation: 'Credit Valuation',
    price_per_bid: 'Price per single bid connect',
    free_allocation: 'Free Allocation',
    initial_credits_desc: 'Initial credits for new nodes',
    freelancer: 'Freelancer',
    client: 'Client',
    
    // Messages
    dialogue_tunnels: 'Dialogue Tunnels',
    secure_matrix: 'Secure communication matrix active',
    search_tunnels: 'Search tunnels...',
    confirm_completion: 'Confirm Completion',
    verified_sync: 'Verified Sync',
    encryption_active: 'End-to-End Encryption Protocol Active',
    type_transmission: 'Type your transmission...',
    initialize_dialogue: 'Initialize Dialogue',
    select_node_sync: 'Select a node from the registry to begin sync',
    
    // Specialists
    specialist_registry: 'Specialist Registry',
    neural_match: 'Neural Match',
    rating_protocol: 'Rating Protocol',
    mastery_level: 'Mastery Level',
    apply_filters: 'Apply Filter Protocol',
    valuation_range: 'Valuation Range',
    mastery_expert: 'Expert',
    mastery_senior: 'Senior',
    mastery_entry: 'Entry',
    domain_software: 'Software Engineering',
    domain_visual: 'Visual Identity',
    domain_data: 'Data Architecture',
    domain_cyber: 'Cyber Security',
    loc_yerevan: 'Yerevan (Main)',
    loc_gyumri: 'Gyumri Cluster',
    loc_dilijan: 'Dilijan Hub',
    loc_remote: 'Remote Sync',
    min: 'Min',
    max: 'Max',
    mastery_expert_yrs: 'Expert (8+ yrs)',
    mastery_intermediate: 'Intermediate',
    mastery_beginner: 'Beginner Node',
    
    // Categories
    cat_software: 'Software Engineering',
    cat_software_desc: 'Full-stack, Backend, and Architectural design.',
    cat_mobile: 'Mobile Ecosystems',
    cat_mobile_desc: 'iOS, Android, and Cross-platform excellence.',
    cat_visual: 'Visual Identity',
    cat_visual_desc: 'High-end UI/UX and brand architecture.',
    cat_data: 'Data Architecture',
    cat_data_desc: 'Neural networks and scalable data models.',
    cat_cyber: 'Cyber Security',
    cat_cyber_desc: 'Infrastructure audits and defense protocols.',
    cat_growth: 'Growth Strategies',
    cat_growth_desc: 'Market penetration and digital presence.',
    
    // Reviews
    review_1: 'The level of technical expertise in the Armenian cluster is unmatched. Synchronized a full banking core in 3 cycles.',
    review_2: 'Architectural precision and perfect communication. The platform handled the escrow protocol flawlessly.',
    review_3: 'Found a specialized neural network engineer within 24 hours. Scaling has never been this efficient.',
    
    // Security
    security_escrow: 'Security Escrow',
    security_desc: 'All value transfers are protected by multi-signature orbital escrow. Funds are only released upon verified milestone completion, ensuring absolute security for both nodes.',
    
    // Auth
    ceo_placeholder: 'CEO at Fintech Solutions',
    specialist_placeholder: 'Senior Neural Infrastructure Architect',
    rate_usd: 'Rate (USD)',
    invalid_code_alert: 'Invalid code. Use 1234 for simulation.',
    code_transmitted: 'Code transmitted to',
    total_rating: 'Total',
    milestones: 'Milestones',
    tier_1: 'TIER 1',
    audit_passed: 'Audit Passed',
    pulse: 'Pulse',
    new_proposal_notif: 'New proposal received for "Neural Architecture"',
    balance_update_notif: 'Balance update: +14,500 AMD',
    
    // Post Job
    post_job: 'Post a Project',
    find_work: 'Find Work',
    budget: 'Budget',
    deadline: 'Deadline',
    mission_registry: 'Mission Registry',
    registry_subtitle: 'Audit active objectives in the Armenia Technical Grid',
    project_protocol: 'Project Protocol',
    fixed_price: 'Fixed Price',
    hourly_sync: 'Hourly Sync',
    retainer_node: 'Retainer Node',
    complexity_level: 'Complexity Level',
    expert_arch: 'Expert Architecture',
    standard_impl: 'Standard Implementation',
    entry_task: 'Entry Task',
    budget_allocation: 'Budget Allocation',
    scan_registry: 'Scan Registry',
    no_missions: 'No active mission objectives detected in the current cycle.',
    proposals_received: 'Proposals Received',
    resource_allocation: 'Resource Allocation',
    audit_objective: 'Audit Objective',
    
    initiate_request: 'Initiate Request',
    broadcasting: 'Broadcasting to elite specialist network',
    objective_title: 'Objective Title',
    operational_domain: 'Operational Domain',
    technical_brief: 'Technical Brief',
    deploy_mission: 'Deploy Mission to Registry',
    abort_deployment: 'Abort Deployment'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Language>('hy');

  useEffect(() => {
    // Mock IP detection logic
    const detectLanguage = async () => {
      try {
        const res = await fetch('https://ipapi.co/json/');
        const data = await res.json();
        if (data.country_code === 'AM') setLang('hy');
        else if (data.country_code === 'RU') setLang('ru');
        else setLang('en');
      } catch (e) {
        setLang('hy'); // Default to hy
      }
    };
    detectLanguage();
  }, []);

  const t = (key: string) => translations[lang][key] || key;

  const formatPrice = (amount: number, forceUSD = false) => {
    if (forceUSD) {
      return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount);
    }
    return new Intl.NumberFormat('hy-AM', { 
      style: 'currency', 
      currency: 'AMD',
      maximumFractionDigits: 0 
    }).format(amount);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, currency: 'AMD', formatPrice }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
