import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'hy' | 'ru' | 'en';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    find_talent: 'Find IT Freelancer',
    find_work: 'Post IT Project',
    login: 'Log In',
    signup: 'Sign Up',
    hero_title: 'Elite IT talent on demand.',
    hero_subtitle: 'Find Senior Developers, DevOps, and Designers from Armenia\'s top tech hub. High quality, clear communication, and secure delivery.',
    get_started: 'Get Started Now',
    find_specialist_btn: 'Find Developer / DevOps / Analyst',
    become_client_btn: 'Become a Client',
    post_project_btn: 'Post IT Project',
    how_it_works_title: 'How it works',
    how_it_works_subtitle: 'The elite delivery pipeline',
    step_1_title: 'Describe IT Task',
    step_1_desc: 'Specify stack, requirements, and budget.',
    step_2_title: 'Get Responses',
    step_2_desc: 'Receive bids from verified top-tier developers.',
    step_3_title: 'Choose Specialist',
    step_3_desc: 'Review portfolios, GitHubs, and previous feedback.',
    step_4_title: 'Secure Payment',
    step_4_desc: 'Release funds only after milestone verification via Escrow.',
    categories_title: 'Core IT Domains',
    categories_subtitle: 'Specialized solutions for every stack',
    cat_web: 'Web Development',
    cat_mobile: 'Mobile Apps',
    cat_backend: 'Backend / API',
    cat_devops: 'DevOps / Infrastructure',
    cat_db: 'Databases',
    cat_testing: 'QA / Testing',
    cat_outsourcing: 'IT Outsourcing',
    cat_automation: 'Automation & Chatbots',
    search_placeholder: 'Who are you looking for? Python, React, DevOps, Analytics...',
    specialists_title: 'Verified IT Specialists',
    specialists_subtitle: 'Top developers ready to start',
    view_profile: 'View Profile',
    price_from: 'from',
    per_hour: '/hr',
    testimonials_title: 'Voices of Excellence',
    testimonials_subtitle: 'Success stories from our IT clients',
    post_project_form_title: 'Publish IT Project',
    project_name: 'Project Name',
    project_category: 'Category',
    project_budget: 'Budget (or "Negotiable")',
    project_desc: 'Description (stack, timeline, requirements)',
    submit_project: 'Submit Project',
    help_choose_btn: 'Help me choose IT specialist',
    footer_desc: 'The leading IT marketplace connecting global businesses with elite Armenian tech specialists. Secure, fast, and professional.',
    made_by: 'Made by',
    all_rights: 'All Rights Reserved',
    nav_dashboard: 'Dashboard',
    nav_find: 'Find Work',
    nav_my_jobs: 'My Jobs',
    nav_catalog: 'Project Catalog',
    nav_messages: 'Messages',
    nav_settings: 'Profile Settings',
    logout: 'Logout Session',
    search_placeholder_freelancer: 'Search for high-tier projects...',
    search_placeholder_client: 'Search for world-class specialists...',
    post_job: 'Post New Project',
    
    // Dashboard new additions
    earnings_month: 'EARNINGS THIS MONTH',
    active_applications: 'ACTIVE APPLICATIONS',
    available_connects: 'AVAILABLE CONNECTS',
    recommended_for_you: 'Recommended for you',
    curated_dna: 'Curated based on your professional DNA',
    view_marketplace: 'View Marketplace',
    top_projects_feed: 'Top Projects Feed',
    no_projects_found: 'No projects found matching',
    module_active: 'Module is active',
    module_desc: 'This section is part of the professional CRM workflow. Ready to integrate data API.',
    account_summary: 'Account Summary',
    profile_completeness: 'Profile completeness:',
    identity_verified: 'Identity verified',
    payment_method: 'Payment method',
    upcoming_deadlines: 'Upcoming Deadlines',
    no_deadlines: 'No active contracts with deadlines.',
    start_agency: 'Start an Agency to scale your business',
    agency_desc: 'Collaborate with other specialists under one banner and win bigger projects.',
    create_agency: 'Create Agency',
    description: 'Description',
    location: 'Location',
    client_label: 'Client',
    submit_proposal: 'Submit Proposal',
    price: 'Price',
    proposals: 'Proposals',
    fixed: 'fixed',
    hourly: 'hourly',
    posted_just_now: 'Just now',
    posted_2h: '2h ago',
    posted_5h: '5h ago',
    posted_1d: '1d ago',
    personal_account: 'Personal Account',
    completed_orders: 'Completed Orders',
    activity_role: 'Activity Role',
    profile_photo: 'Profile Photo',
    language_choice: 'Language Selection',
    contact_specialist: 'Contact',
    about_me: 'Professional Bio',
    projects_count: 'projects',
    no_completed_projects: 'No completed projects yet.',
    nav_language: 'Language',
    nav_category: 'Category',
    nav_experience: 'Experience',
    elite_specialist: 'Elite Specialist',
    marketplace_client: 'Marketplace Client',
    years: 'Years',
    back_to_dashboard: 'Back to Dashboard',
    no_description: 'No description provided.',
    tab_specialists: 'Specialists',
    tab_my_postings: 'My Postings',
    tab_my_applications: 'My Applications',
    tab_project_proposals: 'Project Proposals',
    verified_user: 'Verified',
    platform_activity: 'Platform Activity',
    response_rate: 'Response Rate',
    help_me_choose_title: 'Help Me Choose',
    help_me_choose_desc: 'Unsure which specialist fits your IT project? Get a free 15-min consultation with our technical manager.',
    hire_specialist: 'Hire Specialist',
    view_portfolio: 'View Portfolio',
    review_bids: 'Review Bids',
    applied_for_project: 'Applied for IT Project',
    awaiting_client_review: 'Awaiting Client Review',
    approve_and_hire: 'Approve & Hire',
    find_it_talent: 'Find IT Talent',
    browse_it_projects: 'Browse IT Projects',
    my_workspace: 'My Workspace',
    settings: 'Settings',
    client_dashboard: 'Client Dashboard',
    freelancer_dashboard: 'Freelancer Dashboard',
    main_page: 'Main Page',
    search_projects_placeholder: 'Search IT projects...',
    search_talent_placeholder: 'Search developers, DevOps, designers...',
    post_it_project: 'Post IT Project',
    request_consultation: 'Request Consultation',
    message: 'Message',
    platform: 'Platform',
    support: 'Support',
    average_rating: 'Average Rating',
    premium_ecosystem: 'Premium IT Ecosystem in Armenia',
    agile_business: 'Agile Business',
    spent: 'Spent',
    earned: 'Earned',
    success: 'Success',
    proposals_count: 'Proposals',
    budget: 'Budget',
    email: 'Email',
    telegram: 'Telegram',
    edit_profile: 'Edit Profile'
  },
  ru: {
    find_talent: 'Найти IT-фрилансера',
    find_work: 'Разместить IT-проект',
    login: 'Войти',
    signup: 'Регистрация',
    hero_title: 'Элитные IT-таланты по запросу.',
    hero_subtitle: 'Найдите Senior разработчиков, DevOps и дизайнеров из главного технологического хаба Армении. Высокое качество, четкая коммуникация и безопасная доставка.',
    get_started: 'Начать сейчас',
    find_specialist_btn: 'Найти разработчика / DevOps / аналитика',
    become_client_btn: 'Стать заказчиком',
    post_project_btn: 'Разместить IT-проект',
    how_it_works_title: 'Как это работает',
    how_it_works_subtitle: 'Процесс реализации вашего проекта',
    step_1_title: 'Опишите IT-задачу',
    step_1_desc: 'Укажите стек, требования и бюджет.',
    step_2_title: 'Получите отклики',
    step_2_desc: 'Получайте предложения от проверенных разработчиков.',
    step_3_title: 'Выберите специалиста',
    step_3_desc: 'Изучите портфолио, GitHub и отзывы.',
    step_4_title: 'Безопасная оплата',
    step_4_desc: 'Оплата переводится исполнителю только после проверки этапа через эскроу.',
    categories_title: 'Основные IT-направления',
    categories_subtitle: 'Специализированные решения для любого стека',
    cat_web: 'Веб-разработка',
    cat_mobile: 'Мобильные приложения',
    cat_backend: 'Backend / API',
    cat_devops: 'DevOps / Инфраструктура',
    cat_db: 'Базы данных',
    cat_testing: 'Тестирование / QA',
    cat_outsourcing: 'IT-аутсорсинг',
    cat_automation: 'Автоматизация и чат-боты',
    search_placeholder: 'Кого ищете? Python, React, DevOps, аналитика...',
    specialists_title: 'Проверенные IT-специалисты',
    specialists_subtitle: 'Топ-разработчики, готовые к работе',
    view_profile: 'Профиль',
    price_from: 'от',
    per_hour: '/час',
    testimonials_title: 'Голоса успеха',
    testimonials_subtitle: 'Истории успеха наших IT-заказчиков',
    post_project_form_title: 'Опубликовать IT-заказ',
    project_name: 'Название проекта',
    project_category: 'Категория',
    project_budget: 'Бюджет (или "договорной")',
    project_desc: 'Описание (стек, сроки, требования)',
    submit_project: 'Опубликовать проект',
    help_choose_btn: 'Помочь выбрать IT-специалиста',
    footer_desc: 'Ведущий IT-маркетплейс, соединяющий глобальный бизнес с элитными армянскими IT-специалистами.',
    made_by: 'Сделано компанией',
    all_rights: 'Все права защищены',
    nav_dashboard: 'Панель управления',
    nav_find: 'Поиск работы',
    nav_my_jobs: 'Мои проекты',
    nav_catalog: 'Каталог услуг',
    nav_messages: 'Сообщения',
    nav_settings: 'Настройки профиля',
    logout: 'Выйти из сессии',
    search_placeholder_freelancer: 'Поиск топовых проектов...',
    search_placeholder_client: 'Поиск специалистов мирового уровня...',
    post_job: 'Разместить проект',
    
    // Dashboard new additions
    earnings_month: 'ЗАРАБОТОК В ЭТОМ МЕСЯЦЕ',
    active_applications: 'АКТИВНЫЕ ЗАЯВКИ',
    available_connects: 'ДОСТУПНЫЕ КОННЕКТЫ',
    recommended_for_you: 'Рекомендуем вам',
    curated_dna: 'Подобрано на основе вашего профиля',
    view_marketplace: 'Смотреть биржу',
    top_projects_feed: 'Лента лучших проектов',
    no_projects_found: 'Не найдено проектов по запросу',
    module_active: 'Модуль активен',
    module_desc: 'Этот раздел — часть профессиональной CRM. Готов к интеграции с API.',
    account_summary: 'Сводка аккаунта',
    profile_completeness: 'Заполненность профиля:',
    identity_verified: 'Личность подтверждена',
    payment_method: 'Способ оплаты',
    upcoming_deadlines: 'Ближайшие дедлайны',
    no_deadlines: 'Нет активных контрактов с дедлайнами.',
    start_agency: 'Создайте агентство для масштабирования',
    agency_desc: 'Сотрудничайте с другими специалистами и получайте крупные заказы.',
    create_agency: 'Создать агентство',
    description: 'Описание',
    location: 'Локация',
    client_label: 'Клиент',
    submit_proposal: 'Подать заявку',
    price: 'Цена',
    proposals: 'Заявок',
    fixed: 'фикс.',
    hourly: 'почас.',
    posted_just_now: 'Только что',
    posted_2h: '2ч назад',
    posted_5h: '5ч назад',
    posted_1d: '1д назад',
    personal_account: 'Личный кабинет',
    completed_orders: 'Завершенные заказы',
    activity_role: 'Вид деятельности',
    profile_photo: 'Фотография профиля',
    language_choice: 'Выбор языка',
    contact_specialist: 'Связаться',
    about_me: 'Обо мне',
    projects_count: 'проектов',
    no_completed_projects: 'Пока нет завершенных проектов.',
    nav_language: 'Язык',
    nav_category: 'Категория',
    nav_experience: 'Опыт работы',
    elite_specialist: 'Элитный специалист',
    marketplace_client: 'Заказчик',
    years: 'Лет',
    back_to_dashboard: 'Вернуться в панель',
    no_description: 'Описание не предоставлено.',
    tab_specialists: 'Специалисты',
    tab_my_postings: 'Мои вакансии',
    tab_my_applications: 'Мои отклики',
    tab_project_proposals: 'Предложения по проектам',
    verified_user: 'Подтвержденный',
    platform_activity: 'Активность',
    response_rate: 'Скорость ответа',
    help_me_choose_title: 'Помочь с выбором',
    help_me_choose_desc: 'Не уверены, какой специалист нужен? Получите бесплатную 15-минутную консультацию с нашим тех. менеджером.',
    hire_specialist: 'Нанять специалиста',
    view_portfolio: 'Смотреть портфолио',
    review_bids: 'Отклики',
    applied_for_project: 'Откликнулся на IT проект',
    awaiting_client_review: 'Ожидает рассмотрения',
    approve_and_hire: 'Одобрить и Нанять',
    find_it_talent: 'Найти IT-таланты',
    browse_it_projects: 'Биржа IT-проектов',
    my_workspace: 'Мое пространство',
    settings: 'Настройки',
    client_dashboard: 'Панель заказчика',
    freelancer_dashboard: 'Панель фрилансера',
    main_page: 'Главная',
    search_projects_placeholder: 'Поиск IT-проектов...',
    search_talent_placeholder: 'Поиск разработчиков, DevOps...',
    post_it_project: 'Разместить IT-проект',
    request_consultation: 'Запросить консультацию',
    message: 'Сообщение',
    platform: 'Платформа',
    support: 'Поддержка',
    average_rating: 'Средний рейтинг',
    premium_ecosystem: 'Премиальная IT-экосистема в Армении',
    agile_business: 'Agile Business',
    spent: 'Потрачено',
    earned: 'Заработано',
    success: 'Успех',
    proposals_count: 'Заявок',
    budget: 'Бюджет',
    email: 'Эл. почта',
    telegram: 'Телеграм',
    edit_profile: 'Редактировать профиль'
  },
  hy: {
    find_talent: 'Գտնել IT-ֆրիլանսեր',
    find_work: 'Տեղադրել IT-նախագիծ',
    login: 'Մուտք',
    signup: 'Գրանցում',
    hero_title: 'Էլիտար IT տաղանդներ ըստ պահանջի:',
    hero_subtitle: 'Գտեք Senior ծրագրավորողների, DevOps և դիզայներների Հայաստանի գլխավոր տեխնոլոգիական հաբից: Բարձր որակ, հստակ հաղորդակցություն և անվտանգ առաքում:',
    get_started: 'Սկսել հիմա',
    find_specialist_btn: 'Գտնել ծրագրավորող / DevOps / վերլուծաբան',
    become_client_btn: 'Դառնալ պատվիրատու',
    post_project_btn: 'Տեղադրել IT-նախագիծ',
    how_it_works_title: 'Ինչպես է այն աշխատում',
    how_it_works_subtitle: 'Ձեր նախագծի իրականացման գործընթացը',
    step_1_title: 'Նկարագրեք IT-խնդիրը',
    step_1_desc: 'Նշեք ստեկը, պահանջները և բյուջեն:',
    step_2_title: 'Ստացեք արձագանքներ',
    step_2_desc: 'Ստացեք առաջարկներ ստուգված ծրագրավորողից:',
    step_3_title: 'Ընտրեք մասնագետին',
    step_3_desc: 'Ուսումնասիրեք պորտֆոլիոն, GitHub-ը և կարծիքները:',
    step_4_title: 'Ապահով վճարում',
    step_4_desc: 'Վճարումը փոխանցվում է կատարողին միայն էսքրոուի միջոցով ստուգումից հետո:',
    categories_title: 'Հիմնական IT ուղղությունները',
    categories_subtitle: 'Մասնագիտացված լուծումներ ցանկացած ստեկի համար',
    cat_web: 'Վեբ ծրագրավորում',
    cat_mobile: 'Մոբայլ հավելվածներ',
    cat_backend: 'Backend / API',
    cat_devops: 'DevOps / Ենթակառուցվածք',
    cat_db: 'Տվյալների բազաներ',
    cat_testing: 'Թեստավորում / QA',
    cat_outsourcing: 'IT-աութսորսինգ',
    cat_automation: 'Ավտոմատացում և չաթ-բոտեր',
    search_placeholder: 'Ո՞ւմ եք փնտրում: Python, React, DevOps, վերլուծություն...',
    specialists_title: 'Ստուգված IT մասնագետներ',
    specialists_subtitle: 'Լավագույն ծրագրավորողները, պատրաստ աշխատանքի',
    view_profile: 'Պրոֆիլ',
    contact_specialist: 'Կապ հաստատել',
    price_from: 'սկսած',
    per_hour: '/ժամ',
    testimonials_title: 'Հաջողության ձայներ',
    testimonials_subtitle: 'Մեր IT-պատվիրատուների հաջողության պատմությունները',
    post_project_form_title: 'Հրապարակել IT-պատվեր',
    project_name: 'Նախագծի անվանումը',
    project_category: 'Կատեգորիա',
    project_budget: 'Բյուջե (կամ "պայմանագրային")',
    project_desc: 'Նկարագրություն (ստեկ, ժամկետներ, պահանջները)',
    submit_project: 'Հրապարակել նախագիծ',
    help_choose_btn: 'Օգնեք ընտրել IT մասնագետ',
    footer_desc: 'Առաջատար IT հարթակ, որը միացնում է գլոբալ բիզնեսը հայկական էլիտար IT մասնագետների հետ:',
    made_by: 'Պատրաստված է',
    all_rights: 'Բոլոր իրավունքները պաշտպանված են',
    nav_dashboard: 'Կառավարման վահանակ',
    nav_find: 'Աշխատանքի փնտրում',
    nav_my_jobs: 'Իմ նախագծերը',
    nav_catalog: 'Ծառայությունների կատալոգ',
    nav_messages: 'Հաղորդագրություններ',
    nav_settings: 'Պրոֆիլի կարգավորումներ',
    logout: 'Դուրս գալ',
    search_placeholder_freelancer: 'Փնտրել բարձրակարգ նախագծեր...',
    search_placeholder_client: 'Փնտրել համաշխարհային կարգի մասնագետների...',
    post_job: 'Տեղադրել նախագիծ',
    
    // Dashboard new additions
    earnings_month: 'ԱՅՍ ԱՄՍՎԱ ԵԿԱՄՈՒՏԸ',
    active_applications: 'ԱԿՏԻՎ ՀԱՅՏԵՐ',
    available_connects: 'ՀԱՍԱՆԵԼԻ ԿԱՊԵՐ',
    recommended_for_you: 'Առաջարկվում է ձեզ',
    curated_dna: 'Ընտրված է ըստ ձեր պրոֆիլի',
    view_marketplace: 'Դիտել շուկան',
    top_projects_feed: 'Լավագույն նախագծերի ժապավեն',
    no_projects_found: 'Ոչ մի նախագիծ չի գտնվել',
    module_active: 'Մոդուլն ակտիվ է',
    module_desc: 'Այս բաժինը պրոֆեսիոնալ CRM-ի մաս է: Պատրաստ է API ինտեգրման:',
    account_summary: 'Հաշվի ամփոփում',
    profile_completeness: 'Պրոֆիլի լրացվածություն՝',
    identity_verified: 'Ինքնությունը հաստատված է',
    payment_method: 'Վճարման եղանակ',
    upcoming_deadlines: 'Առաջիկա վերջնաժամկետներ',
    no_deadlines: 'Չկան ակտիվ պայմանագրեր վերջնաժամկետներով:',
    start_agency: 'Ստեղծեք գործակալություն՝ ընդլայնելու համար',
    agency_desc: 'Համագործակցեք այլ մասնագետների հետ և ստացեք խոշոր նախագծեր:',
    create_agency: 'Ստեղծել գործակալություն',
    description: 'Նկարագրություն',
    location: 'Գտնվելու վայրը',
    client_label: 'Պատվիրատու',
    submit_proposal: 'Ներկայացնել հայտ',
    price: 'Գին',
    proposals: 'Հայտեր',
    fixed: 'ֆիքսված',
    hourly: 'ժամավճար',
    posted_just_now: 'Քիչ առաջ',
    posted_2h: '2ժ առաջ',
    posted_5h: '5ժ առաջ',
    posted_1d: '1օր առաջ',
    about_me: 'Իմ մասին',
    projects_count: 'նախագծեր',
    no_completed_projects: 'Դեռ չկան ավարտված նախագծեր:',
    nav_language: 'Լեզու',
    nav_category: 'Կատեգորիա',
    nav_experience: 'Աշխատանքային փորձ',
    elite_specialist: 'Էլիտար մասնագետ',
    marketplace_client: 'Պատվիրատու',
    years: 'Տարի',
    back_to_dashboard: 'Վերադառնալ վահանակ',
    no_description: 'Նկարագրություն տրամադրված չէ:',
    tab_specialists: 'Մասնագետներ',
    tab_my_postings: 'Իմ հայտարարությունները',
    tab_my_applications: 'Իմ դիմումները',
    tab_project_proposals: 'Նախագծի առաջարկներ',
    verified_user: 'Հաստատված',
    platform_activity: 'Ակտիվություն',
    response_rate: 'Արձագանքի արագություն',
    help_me_choose_title: 'Օգնեք ընտրել',
    help_me_choose_desc: 'Չգիտե՞ք, թե որ մասնագետն է համապատասխանում: Ստացեք անվճար 15 րոպեանոց խորհրդատվություն:',
    hire_specialist: 'Վարձել մասնագետ',
    view_portfolio: 'Դիտել պորտֆոլիոն',
    review_bids: 'Դիտել առաջարկները',
    applied_for_project: 'Դիմել է IT նախագծի համար',
    awaiting_client_review: 'Սպասում է պատվիրատուի հաստատմանը',
    approve_and_hire: 'Հաստատել և վարձել',
    find_it_talent: 'Գտնել IT տաղանդներ',
    browse_it_projects: 'Դիտել IT նախագծերը',
    my_workspace: 'Իմ աշխատավայրը',
    settings: 'Կարգավորումներ',
    client_dashboard: 'Պատվիրատուի վահանակ',
    freelancer_dashboard: 'Ֆրիլանսերի վահանակ',
    main_page: 'Գլխավոր էջ',
    search_projects_placeholder: 'Փնտրել IT նախագծեր...',
    search_talent_placeholder: 'Փնտրել ծրագրավորողների, DevOps...',
    post_it_project: 'Տեղադրել IT նախագիծ',
    request_consultation: 'Հարցնել խորհրդատվություն',
    message: 'Հաղորդագրություն',
    platform: 'Հարթակ',
    support: 'Աջակցություն',
    average_rating: 'Միջին վարկանիշ',
    premium_ecosystem: 'Պրեմիում IT էկոհամակարգ Հայաստանում',
    agile_business: 'Agile Business',
    spent: 'Ծախսված',
    earned: 'Վաստակած',
    success: 'Հաջողություն',
    proposals_count: 'Հայտեր',
    budget: 'Բյուջե',
    email: 'Էլ. փոստ',
    telegram: 'Տելեգրամ',
    edit_profile: 'Խմբագրել պրոֆիլը'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLang] = useState<Language>('en');

  // Auto-localization based on IP (using free service)
  useEffect(() => {
    const fetchLocation = async () => {
      try {
        const response = await fetch('https://ipapi.co/json/');
        const data = await response.json();
        const countryCode = data.country_code;
        
        if (countryCode === 'AM') {
          setLang('hy');
        } else if (['RU', 'BY', 'KZ', 'KG'].includes(countryCode)) {
          setLang('ru');
        } else {
          setLang('en');
        }
      } catch (error) {
        // Fallback to browser language if API fails
        const browserLang = navigator.language.split('-')[0];
        if (['ru', 'en', 'hy'].includes(browserLang)) {
          setLang(browserLang as Language);
        }
      }
    };

    fetchLocation();
  }, []);

  const t = (key: string) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
